const KEY="yourSongbookV2";
const notes=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
const instruments={baritone:{label:"Baritone Ukulele",tuning:"DGBE",strings:4},soprano:{label:"Soprano Ukulele",tuning:"GCEA",strings:4},guitar:{label:"Guitar",tuning:"EADGBE",strings:6}};
const shapes={baritone:{G:[0,0,0,3],Em:[0,3,4,2],C:[0,0,0,0],D:[2,2,2,0],B:[4,4,4,2],F:[2,0,1,0],Am:[2,0,0,0],A:[1,1,0,0],E:[4,4,4,2],F#m:[1,1,1,1],F#m7:[1,1,1,3]},soprano:{G:[0,2,3,2],Em:[0,4,3,2],C:[0,0,0,3],D:[2,2,2,0],B:[4,4,4,2],F:[2,0,1,0],Am:[2,0,0,0],A:[1,1,0,0],E:[1,4,0,2],F#m:[2,1,2,0],F#m7:[2,1,2,2]},guitar:{G:[3,2,0,0,0,3],Em:[0,2,2,0,0,0],C:[null,3,2,0,1,0],D:[null,0,0,2,3,2],B:[null,2,4,4,4,2],F:[1,3,3,2,1,1],Am:[null,0,2,2,1,0],A:[null,0,2,2,2,0],E:[0,2,2,1,0,0],F#m:[2,4,4,2,2,2],F#m7:[2,4,2,2,2,2]}};
const baseSong={id:"hallelujah",title:"Hallelujah",artist:"Leonard Cohen",key:"G",genre:"Folk",moods:["Reflective","Singalong"],duration:300,source:{type:"PDF",name:"HALLELUJAH in key of G.pdf",credit:"Beginner ukulele arrangement by Cynthia Lin"},sections:[
{name:"Intro / Break",lines:[{text:"",chords:[{name:"G",pos:0},{name:"Em",pos:0},{name:"G",pos:0},{name:"Em",pos:0}]}]},
{name:"Verse 1",lines:[
{text:"Well I've heard there was a secret chord — That David played and it pleased the Lord",chords:[{name:"G",pos:0},{name:"Em",pos:7}]},
{text:"But you don't really care for music, do you?",chords:[{name:"C",pos:0},{name:"D",pos:6}]},
{text:"Well it goes like this: the fourth, the fifth, the minor fall and the major lift",chords:[{name:"G",pos:0},{name:"C",pos:6},{name:"D",pos:10},{name:"Em",pos:26},{name:"C",pos:35}]},
{text:"The baffled king composing Halle-lujah",chords:[{name:"D",pos:0},{name:"B",pos:3},{name:"Em",pos:18},{name:"Em",pos:32}]}
]},
{name:"Chorus",lines:[
{text:"Halle-lujah Halle-lujah",chords:[{name:"C",pos:0},{name:"C",pos:12},{name:"Em",pos:0},{name:"Em",pos:12}]},
{text:"Halle-lu-u-jah",chords:[{name:"C",pos:0},{name:"C",pos:8},{name:"G",pos:8},{name:"D",pos:9},{name:"G",pos:12},{name:"Em",pos:12},{name:"G",pos:14},{name:"Em",pos:14}]}
]},
{name:"Verse 2",lines:[{text:"Your faith was strong but you needed proof",chords:[{name:"G",pos:0},{name:"Em",pos:5}]},{text:"You saw her bathing on the roof",chords:[{name:"C",pos:0},{name:"D",pos:5}]},{text:"Her beauty and the moonlight overthrew you",chords:[{name:"G",pos:0},{name:"C",pos:5},{name:"D",pos:12},{name:"Em",pos:24},{name:"C",pos:31}]},{text:"She tied you to a kitchen chair",chords:[{name:"D",pos:0},{name:"B",pos:5},{name:"Em",pos:22},{name:"Em",pos:31}]},{text:"She broke your throne, and she cut your hair",chords:[{name:"C",pos:0},{name:"C",pos:13},{name:"Em",pos:20},{name:"Em",pos:30}]},{text:"And from your lips she drew the Hallelujah",chords:[{name:"C",pos:0},{name:"C",pos:13},{name:"G",pos:20},{name:"D",pos:24},{name:"G",pos:29},{name:"Em",pos:29},{name:"G",pos:31},{name:"Em",pos:31}]}]},
{name:"Verse 3",lines:[{text:"You say I took the name in vain",chords:[{name:"G",pos:0},{name:"Em",pos:6}]},{text:"I don't even know the name",chords:[{name:"C",pos:0},{name:"D",pos:6}]},{text:"But if I did, well really, what's it to you?",chords:[{name:"G",pos:0},{name:"C",pos:9},{name:"D",pos:17},{name:"Em",pos:29},{name:"C",pos:36}]},{text:"There's a blaze of light in every word",chords:[{name:"D",pos:0},{name:"B",pos:5},{name:"Em",pos:25},{name:"Em",pos:31}]},{text:"It doesn't matter which you heard",chords:[{name:"C",pos:0},{name:"C",pos:13},{name:"Em",pos:20},{name:"Em",pos:29}]},{text:"The holy or the broken Hallelujah",chords:[{name:"C",pos:0},{name:"C",pos:13},{name:"G",pos:24},{name:"D",pos:29},{name:"G",pos:34},{name:"Em",pos:34},{name:"G",pos:36},{name:"Em",pos:36}]}]},
{name:"Verse 4",lines:[{text:"I did my best, it wasn't much",chords:[{name:"G",pos:0},{name:"Em",pos:5}]},{text:"I couldn't feel, so I tried to touch",chords:[{name:"C",pos:0},{name:"D",pos:6}]},{text:"I've told the truth, I didn't come to fool you",chords:[{name:"G",pos:0},{name:"C",pos:13},{name:"D",pos:18},{name:"Em",pos:30},{name:"C",pos:37}]},{text:"And even though it all went wrong",chords:[{name:"D",pos:0},{name:"B",pos:7},{name:"Em",pos:23},{name:"Em",pos:31}]},{text:"I'll stand before the Lord of Song",chords:[{name:"C",pos:0},{name:"C",pos:13},{name:"Em",pos:20},{name:"Em",pos:31}]},{text:"With nothing on my tongue but Hallelujah",chords:[{name:"C",pos:0},{name:"C",pos:16},{name:"G",pos:25},{name:"D",pos:30},{name:"G",pos:35},{name:"Em",pos:35},{name:"G",pos:37},{name:"Em",pos:37}]}]},
{name:"Final Chorus",lines:[{text:"Halle-lujah Halle-lujah",chords:[{name:"C",pos:0},{name:"C",pos:12},{name:"Em",pos:0},{name:"Em",pos:12}]},{text:"Halle-lu-u-jah",chords:[{name:"C",pos:0},{name:"C",pos:8},{name:"G",pos:8},{name:"D",pos:9}]},{text:"Halle-lujah Halle-lujah",chords:[{name:"C",pos:0},{name:"C",pos:12},{name:"Em",pos:0},{name:"Em",pos:12}]},{text:"Halle-lu-u-jah",chords:[{name:"C",pos:0},{name:"C",pos:8},{name:"G",pos:8},{name:"D",pos:9},{name:"G",pos:12}]}
]}]};
function uid(p="id"){return p+"_"+Date.now().toString(36)+"_"+Math.random().toString(36).slice(2,7)}
function initial(){return {songs:{hallelujah:structuredClone(baseSong)},sets:{},settings:{instrument:"baritone",transpose:0,view:"scroll",pin:true},session:{view:"library",songId:null,setId:null,performanceIndex:0},originals:{}}}
let state=load();
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x&&x.songs?x:initial()}catch(e){return initial()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function transposeChord(ch,n){const m=String(ch).match(/^([A-G](?:#|b)?)(.*)$/);if(!m)return ch;let root=m[1].replace("Db","C#").replace("Eb","D#").replace("Gb","F#").replace("Ab","G#").replace("Bb","A#");let i=notes.indexOf(root);if(i<0)return ch;return notes[(i+n+120)%12]+m[2]}
function allChords(song){const a=[];song.sections.forEach(s=>s.lines.forEach(l=>l.chords.forEach(c=>{if(c.name&&!a.includes(c.name))a.push(c.name)})));return a}
function chordDiagram(name){const f=shapes[state.settings.instrument]?.[name];if(!f)return '<div class="fingering">diagram coming soon</div>';const n=f.length;let svg='<svg viewBox="0 0 70 64" aria-label="'+esc(name)+' chord diagram">';for(let i=0;i<4;i++)svg+=`<line x1="${12+i*12}" y1="15" x2="${12+i*12}" y2="58" stroke="#777"/>`;for(let i=0;i<5;i++)svg+=`<line x1="12" y1="${15+i*10}" x2="48" y2="${15+i*10}" stroke="#777"/>`;f.forEach((v,i)=>{if(v===null)svg+=`<text x="${12+i*12}" y="10" text-anchor="middle" font-size="9">×</text>`;else if(v===0)svg+=`<circle cx="${12+i*12}" cy="15" r="3" fill="none" stroke="#526b4d"/>`;else svg+=`<circle cx="${12+i*12}" cy="${15+(Math.min(v,4)-.5)*10}" r="4" fill="#526b4d"/>`});return svg+'</svg>'}
function getSong(){return state.songs[state.session.songId]}
function renderLibrary(){const q=(document.querySelector("#search")?.value||"").toLowerCase();const songs=Object.values(state.songs).filter(s=>(s.title+" "+s.artist+" "+s.genre+" "+s.moods.join(" ")).toLowerCase().includes(q));document.querySelector("#libraryList").innerHTML=songs.map(s=>`<div class="songRow"><div class="songInfo"><button data-song="${s.id}"><div class="songName">${esc(s.title)}</div><div class="songMeta">${esc(s.artist)} · Key of ${esc(s.key)} · ${Math.round(s.duration/60)} min</div><div class="tags">${s.moods.map(m=>'<span class="tag">'+esc(m)+'</span>').join("")}</div></button></div><button class="btn" data-song-edit="${s.id}">Edit</button></div>`).join("")||'<div class="empty">No songs found.</div>';document.querySelectorAll("[data-song]").forEach(b=>b.onclick=()=>openSong(b.dataset.song));document.querySelectorAll("[data-song-edit]").forEach(b=>b.onclick=()=>openSong(b.dataset.songEdit,true))}
function openSong(id,edit=false){state.session.view="song";state.session.songId=id;state.session.setId=null;state.session.edit=edit;save();render()}
function renderSong(){const s=getSong();if(!s)return openLibrary();document.querySelector("#songTitle").textContent=s.title;document.querySelector("#songMeta").textContent=s.artist+" · "+(s.source?.credit||"Song");document.querySelector("#songDetails").textContent=[`Key of ${transposeChord(s.key,state.settings.transpose)}`,s.genre,s.moods.join(" · "),Math.round(s.duration/60)+" min"].filter(Boolean).join(" · ");document.querySelector("#instrument").value=state.settings.instrument;document.querySelector("#viewMode").value=state.settings.view;document.querySelector("#pinToggle").textContent=state.settings.pin?"📌 Chord bar on":"📌 Chord bar off";document.querySelector("#key").innerHTML=notes.map(n=>'<option>'+n+'</option>').join("");document.querySelector("#key").value=transposeChord(s.key,state.settings.transpose);renderChordStrip(s);renderLyrics(s);document.querySelector("#songEdit").textContent=state.session.edit?"Done":"Edit"}
function renderChordStrip(s){const names=allChords(s);const el=document.querySelector("#chords");el.innerHTML=names.map(n=>{const x=transposeChord(n,state.settings.transpose);return `<div class="chordbox"><div class="chordname">${esc(x)}</div><div class="diagram">${chordDiagram(x)}</div></div>`}).join("");el.style.position=state.settings.pin?"sticky":"static"}
function renderLyrics(s){const el=document.querySelector("#lyrics");el.className="card lyrics"+(state.settings.view==="page"?" page":"");if(state.session.edit){el.innerHTML=s.sections.map((sec,si)=>`<div class="sectionEdit"><h3>${esc(sec.name)}</h3>${sec.lines.map((l,li)=>renderEditorLine(l,si,li)).join("")}<button class="btn" data-add-line="${si}">＋ Add line</button></div>`).join("")+'<button class="btn" id="addSection">＋ Add section</button>';bindEditor()}else{el.innerHTML=s.sections.map(sec=>`<section class="section"><h3>${esc(sec.name)}</h3>${sec.lines.map(renderDisplayLine).join("")}</section>`).join("")}}
function renderDisplayLine(l){const text=l.text||"";if(!text.trim())return '<div class="songLine"><div class="lineWords">'+l.chords.map(c=>`<span class="wordCell"><span class="lineChord">${esc(transposeChord(c.name,state.settings.transpose))}</span><span>&nbsp;</span></span>`).join("")+'</div></div>';const by={};l.chords.forEach(c=>{const p=Math.max(0,Math.min(text.length,Number(c.pos)||0));(by[p]??=[]).push(c)});const cuts=[0,...Object.keys(by).map(Number),text.length].sort((a,b)=>a-b).filter((x,i,a)=>i===0||x!==a[i-1]);let html="";for(let i=0;i<cuts.length-1;i++){const p=cuts[i],end=cuts[i+1];if(by[p])html+=`<span class="wordCell"><span class="lineChord">${by[p].map(c=>esc(transposeChord(c.name,state.settings.transpose))).join(" ")}</span><span>${esc(text.slice(p,end))}</span></span>`;else html+=`<span class="wordCell"><span class="lineChord">&nbsp;</span><span>${esc(text.slice(p,end))}</span></span>`}return '<div class="songLine"><div class="lineWords">'+html+'</div></div>'}
function renderEditorLine(l,si,li){return `<div class="editorLine" data-si="${si}" data-li="${li}"><textarea class="lyricInput">${esc(l.text)}</textarea><div class="chordRows">${l.chords.map((c,ci)=>`<div class="chordRow" data-ci="${ci}"><input class="chordName" value="${esc(c.name)}"><select class="chordPos">${positionOptions(l.text,c.pos)}</select><button class="deleteChord">×</button></div>`).join("")}</div><button class="btn addChord">＋ Chord</button></div>`}
function positionOptions(text,pos){const words=[...text.matchAll(/\S+/g)];return words.map((m,i)=>`<option value="${m.index}" ${Number(pos)===m.index?"selected":""}>${i+1}: ${esc(m[0].slice(0,24))}</option>`).join("")||'<option value="0">start</option>'}
function bindEditor(){document.querySelectorAll(".editorLine").forEach(row=>{row.querySelector(".addChord").onclick=()=>{syncEditor();const l=getSong().sections[row.dataset.si].lines[row.dataset.li];l.chords.push({name:"C",pos:0});renderSong()};row.querySelectorAll(".deleteChord").forEach(b=>b.onclick=()=>{syncEditor();getSong().sections[row.dataset.si].lines[row.dataset.li].chords.splice(Number(b.closest(".chordRow").dataset.ci),1);renderSong()})});document.querySelectorAll("[data-add-line]").forEach(b=>b.onclick=()=>{syncEditor();getSong().sections[b.dataset.addLine].lines.push({text:"New lyric line",chords:[]});renderSong()});document.querySelector("#addSection").onclick=()=>{syncEditor();getSong().sections.push({name:"New section",lines:[]});renderSong()}}
function syncEditor(){const s=getSong();document.querySelectorAll(".editorLine").forEach(row=>{const l=s.sections[row.dataset.si].lines[row.dataset.li];l.text=row.querySelector(".lyricInput").value;l.chords=[...row.querySelectorAll(".chordRow")].map(r=>({name:r.querySelector(".chordName").value.trim()||"C",pos:Number(r.querySelector(".chordPos").value)||0}))});save()}
function setView(v){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));const map={library:"libraryView",song:"songView",sets:"setsView",setEditor:"setEditorView",performance:"performanceView",import:"importView"};document.querySelector("#"+map[v]).classList.remove("hidden");document.querySelectorAll(".navbtn").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelector("#back").classList.toggle("hidden",v==="library"||v==="sets"||v==="import")}
function render(){setView(state.session.view);if(state.session.view==="library")renderLibrary();if(state.session.view==="song")renderSong();if(state.session.view==="sets")renderSets();if(state.session.view==="setEditor")renderSetEditor();if(state.session.view==="performance")renderPerformance();if(state.session.view==="import")renderImport()}
function openLibrary(){if(state.session.edit){syncEditor();state.session.edit=false}state.session.view="library";state.session.songId=null;save();render()}
function renderSets(){const el=document.querySelector("#setsList");const sets=Object.values(state.sets);el.innerHTML=sets.map(set=>{const secs=set.songIds.reduce((a,id)=>a+(state.songs[id]?.duration||0),0);return `<div class="card setCard"><h2>${esc(set.name)}</h2><p class="muted">${set.songIds.length} songs · ${Math.round(secs/60)} min</p><button class="primary" data-set="${set.id}">Open set</button></div>`}).join("")||'<div class="card empty">No setlists yet. Create one to start arranging songs.</div>';document.querySelectorAll("[data-set]").forEach(b=>openSet(b.dataset.set))}
function openSet(id){state.session.view="setEditor";state.session.setId=id;save();render()}
function renderSetEditor(){const set=state.sets[state.session.setId];if(!set)return state.session.view="sets",render();const secs=set.songIds.reduce((a,id)=>a+(state.songs[id]?.duration||0),0);document.querySelector("#setTitle").textContent=set.name;document.querySelector("#setSummary").textContent=set.songIds.length+" songs · "+Math.round(secs/60)+" min";const q=(document.querySelector("#setSearch")?.value||"").toLowerCase();document.querySelector("#setLibrary").innerHTML=Object.values(state.songs).filter(s=>(s.title+" "+s.artist+" "+s.genre+" "+s.moods.join(" ")).toLowerCase().includes(q)).map(s=>`<div class="checkRow"><button class="btn" data-add-set="${s.id}">${set.songIds.includes(s.id)?"✓ Added":"+ Add"}</button><span><b>${esc(s.title)}</b><br><span class="muted">${esc(s.artist)} · ${Math.round(s.duration/60)} min</span></span></div>`).join("");document.querySelector("#setSongs").innerHTML=set.songIds.map((id,i)=>{const s=state.songs[id];return s?`<div class="setSongRow" draggable="true" data-order="${i}"><span class="drag">☷</span><span><b>${esc(s.title)}</b><br><span class="muted">${Math.round(s.duration/60)} min</span></span><button class="remove" data-remove-set="${id}">×</button></div>`:''}).join("")||'<div class="empty">Add songs above.</div>';bindSetEditor()}
function bindSetEditor(){document.querySelectorAll("[data-add-set]").forEach(b=>b.onclick=()=>{const set=state.sets[state.session.setId];if(!set.songIds.includes(b.dataset.addSet))set.songIds.push(b.dataset.addSet);save();renderSetEditor()});document.querySelectorAll("[data-remove-set]").forEach(b=>b.onclick=()=>{state.sets[state.session.setId].songIds=state.sets[state.session.setId].songIds.filter(x=>x!==b.dataset.removeSet);save();renderSetEditor()});let dragged=null;document.querySelectorAll("[data-order]").forEach(row=>{row.ondragstart=()=>dragged=Number(row.dataset.order);row.ondragover=e=>e.preventDefault();row.ondrop=()=>{const target=Number(row.dataset.order),a=state.sets[state.session.setId].songIds,x=a.splice(dragged,1)[0];a.splice(target,0,x);save();renderSetEditor()}})}
function renderPerformance(){const set=state.sets[state.session.setId];if(!set)return;const id=set.songIds[state.session.performanceIndex]||set.songIds[0];const s=state.songs[id];if(!s)return;document.querySelector("#performanceCount").textContent=(state.session.performanceIndex+1)+" / "+set.songIds.length;document.querySelector("#performanceSong").innerHTML=`<div class="card"><div class="eyebrow">${esc(set.name)}</div><h1>${esc(s.title)}</h1><p class="sub">${esc(s.artist)} · Key of ${esc(transposeChord(s.key,state.settings.transpose))}</p></div><div class="card lyrics">${s.sections.map(sec=>`<section class="section"><h3>${esc(sec.name)}</h3>${sec.lines.map(renderDisplayLine).join("")}</section>`).join("")}</div>`}
function renderImport(){document.querySelector("#importStatus").textContent=state.originals.pending?("Attached: "+state.originals.pending.name):""}
function parseText(raw){const lines=raw.split(/\r?\n/);const sections=[];let current={name:"Song",lines:[]};sections.push(current);lines.forEach(rawLine=>{const line=rawLine.trimEnd();if(/^\s*(intro|verse|chorus|bridge|outro|break|final chorus)\s*:?\s*$/i.test(line)){current={name:line.replace(/:$/,"").trim(),lines:[]};sections.push(current);return}const ms=[...line.matchAll(/(^|\s)([A-G](?:#|b)?(?:m|maj7|7|sus2|sus4|dim|aug)?)(?=\s|$)/g)];const chords=ms.map(m=>({name:m[2],pos:m.index+(m[1]?m[1].length:0)}));const text=line.replace(/(^|\s)[A-G](?:#|b)?(?:m|maj7|7|sus2|sus4|dim|aug)?(?=\s|$)/g," ").replace(/\s+/g," ").trim();current.lines.push({text,chords})});return sections.filter(s=>s.lines.length)}
document.querySelectorAll(".navbtn").forEach(b=>b.onclick=()=>{if(state.session.edit)syncEditor();state.session.view=b.dataset.view;save();render()});
document.querySelector("#back").onclick=()=>openLibrary();
document.querySelector("#search").oninput=renderLibrary;
document.querySelector("#songEdit").onclick=()=>{if(state.session.edit)syncEditor();state.session.edit=!state.session.edit;renderSong()};
document.querySelector("#instrument").onchange=e=>{if(state.session.edit)syncEditor();state.settings.instrument=e.target.value;save();renderSong()};
document.querySelector("#viewMode").onchange=e=>{state.settings.view=e.target.value;save();renderSong()};
document.querySelector("#pinToggle").onclick=()=>{state.settings.pin=!state.settings.pin;save();renderSong()};
document.querySelector("#up").onclick=()=>{if(state.session.edit)syncEditor();state.settings.transpose++;save();renderSong()};
document.querySelector("#down").onclick=()=>{if(state.session.edit)syncEditor();state.settings.transpose--;save();renderSong()};
document.querySelector("#key").onchange=e=>{const s=getSong();if(state.session.edit)syncEditor();state.settings.transpose=notes.indexOf(e.target.value)-notes.indexOf(s.key);save();renderSong()};
document.querySelector("#newSong").onclick=()=>{const id=uid("song");state.songs[id]={id,title:"New Song",artist:"Unknown",key:"C",genre:"",moods:[],duration:180,source:{type:"Manual"},sections:[{name:"Verse",lines:[{text:"Add lyrics here",chords:[{name:"C",pos:0}]}]}]};openSong(id,true)};
document.querySelector("#newSet").onclick=()=>{const id=uid("set");state.sets[id]={id,name:"New Set",songIds:[]};openSet(id)};
document.querySelector("#setDone").onclick=()=>{state.session.view="sets";save();render()};
document.querySelector("#setSearch").oninput=()=>renderSetEditor();
document.querySelector("#performSet").onclick=()=>{state.session.performanceIndex=0;state.session.view="performance";save();render()};
document.querySelector("#exitPerformance").onclick=()=>{state.session.view="setEditor";save();render()};
document.querySelector("#performanceEdit").onclick=()=>{state.session.view="setEditor";save();render()};
document.querySelector("#prevSong").onclick=()=>{state.session.performanceIndex=Math.max(0,state.session.performanceIndex-1);save();renderPerformance()};
document.querySelector("#nextSong").onclick=()=>{const set=state.sets[state.session.setId];state.session.performanceIndex=Math.min(set.songIds.length-1,state.session.performanceIndex+1);save();renderPerformance()};
document.querySelector("#parseImport").onclick=()=>{const raw=document.querySelector("#importText").value.trim();if(!raw)return;const sections=parseText(raw);const id=uid("song");const firstLine=raw.split(/\r?\n/).find(x=>x.trim())||"Imported Song";state.songs[id]={id,title:firstLine.replace(/\[.*?\]/g,"").trim().slice(0,60)||"Imported Song",artist:"Imported",key:"C",genre:"",moods:[],duration:180,source:{type:"Imported text"},sections};state.session.view="song";state.session.songId=id;state.session.edit=true;save();render()};
document.querySelector("#importFile").onchange=e=>{const f=e.target.files[0];if(!f)return;state.originals.pending={name:f.name,type:f.type,size:f.size};save();renderImport();if(f.type.startsWith("text/")){const reader=new FileReader();reader.onload=()=>{document.querySelector("#importText").value=reader.result};reader.readAsText(f)}};
document.querySelector("#modalCancel").onclick=()=>document.querySelector("#modal").classList.add("hidden");
render();